#!/usr/bin/env bash


git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin


# --------------------------
# Getting Berkeley DB
mkdir bdb
cd bdb
wget https://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
tar -xvf db-4.8.30.tar.gz
cd db-4.8.30/build_unix
mkdir -p build
BDB_PREFIX=$(pwd)/build
chmod u+w ../dbinc/atomic.h
vim ../dbinc/atomic.h  # change __atomic_compare_exchange to __atomic_compare_exchange_db
../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
make install
cd ../../..
# --------------------------


# select the wanted version
git checkout v0.18.1
./autogen.sh
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --with-gui
make
