#!/usr/bin/env bash

cd $(dirname $0)
./tmux-kill
pkill bitcoind
rm -rf lightning-dirs/1   \
       lightning-dirs/2   \
       lightning-dirs/3   \
       dev/*.tmp          \
       ~/.bitcoin         \

