#!/usr/bin/env bash

cd $(dirname $0)
./tmux-kill
rm -rf dev/alice/*              \
       dev/bob/*                \
       dev/charlie/*            \
       ~/.btcd                  \
       ~/.lnd                   \
       dev/identity-pubkey-*    \
       dev/address.*
