#!/usr/bin/env bash

lncli-alice(){
    builtin cd $LNPATH/lnd/1;
    lncli --rpcserver=localhost:10001 --macaroonpath=data/chain/bitcoin/regtest/admin.macaroon $*
    builtin cd - > /dev/null # return to previous directory
}
export -f lncli-alice


lncli-bob(){
    builtin cd $LNPATH/lnd/2;
    lncli --rpcserver=localhost:10002 --macaroonpath=data/chain/bitcoin/regtest/admin.macaroon $*
    builtin cd - > /dev/null
}
export -f lncli-bob


lncli-charlie(){
    builtin cd $LNPATH/lnd/3;
    lncli --rpcserver=localhost:10003 --macaroonpath=data/chain/bitcoin/regtest/admin.macaroon $*
    builtin cd - > /dev/null
}
export -f lncli-charlie

