#!/usr/bin/env bash

# NOTE: convention: every command that dumps data to file (e.g. to be used with
# another command) adds a .tmp suffix. this way they can all be removed easily


# run bitcoin node
bitcoind


# run lightning nodes
run-lightningd 1
run-lightningd 2
run-lightningd 3


# get the nodes identity_pubkey
lcli-alice getinfo | jq -r ".id" > id.alice.tmp
lcli-bob getinfo | jq -r ".id" > id.bob.tmp
lcli-charlie getinfo | jq -r ".id" > id.charlie.tmp

ALICE_ID=$(cat id.alice.tmp)
BOB_ID=$(cat id.bob.tmp)
CHARLIE_ID=$(cat id.charlie.tmp)


# get addresses
lcli-alice newaddr | jq -r ".address" > address.alice.tmp
lcli-bob newaddr | jq -r ".address" > address.bob.tmp
lcli-charlie newaddr | jq -r ".address" > address.charlie.tmp

ALICE_ADDR=$(cat address.alice.tmp)
BOB_ADDR=$(cat address.bob.tmp)
CHARLIE_ADDR=$(cat address.charlie.tmp)


# funding
bitcoin-cli getnewaddress > address.main.tmp
ADDR_MAIN=$(cat address.main.tmp)
mine(){
    BLOCKS_TO_MINE=$1
    bitcoin-cli generatetoaddress $BLOCKS_TO_MINE $ADDR_MAIN
}
mine 400 > /dev/null
bitcoin-cli sendmany "" "{\"${ALICE_ADDR}\":1,\"${BOB_ADDR}\":1,\"${CHARLIE_ADDR}\":1}" > initial.balance.txid.tmp
mine 1 > /dev/null


# see the UTXOs of this wallet
lcli-alice listfunds
lcli-bob listfunds
lcli-charlie listfunds


# connect the nodes
lcli-alice connect $BOB_ID localhost:10002
lcli-charlie connect $BOB_ID localhost:10002


# open channels
lcli-alice fundchannel $BOB_ID 10000000 | jq -r ".txid" > alice-bob.funding.txid.tmp
mine 6 # mine 6 blocks so the channel is considered valid
lcli-bob fundchannel $CHARLIE_ID 10000000 | jq -r ".txid" > bob-charlie.funding.txid.tmp
mine 6


# list open channels
lcli-bob listchannels


# make payment
lcli-charlie invoice 1000000sat "label$(date +%s)" description | jq -r ".bolt11" > charlie.invoice.bolt11.tmp
lcli-alice decodepay $(cat charlie.invoice.bolt11.tmp)
lcli-alice pay $(cat charlie.invoice.bolt11.tmp)


# close channel
lcli-alice close $BOB_ID | jq -r ".txid" > alice-bob.closing.txid.tmp
mine 1

lcli-charlie close $BOB_ID | jq -r ".txid" > charlie-bob.closing.txid.tmp
mine 1