#!/usr/bin/env bash

# NOTE: convention: every command that dumps data to file (e.g. to be used with
# another command) adds a .tmp suffix. this way they can all be removed easily


# run bitcoin node
bitcoind


# run lightning nodes
run-lightningd 1
run-lightningd 2
run-lightningd 3


# get the nodes identity_pubkey
lcli-alice getinfo | jq -r ".id" > id.alice.tmp
lcli-bob getinfo | jq -r ".id" > id.bob.tmp
lcli-charlie getinfo | jq -r ".id" > id.charlie.tmp

ALICE_ID=$(cat id.alice.tmp)
BOB_ID=$(cat id.bob.tmp)
CHARLIE_ID=$(cat id.charlie.tmp)


# get addresses
lcli-alice newaddr | jq -r ".address" > address.alice.tmp
lcli-bob newaddr | jq -r ".address" > address.bob.tmp
lcli-charlie newaddr | jq -r ".address" > address.charlie.tmp

ALICE_ADDR=$(cat address.alice.tmp)
BOB_ADDR=$(cat address.bob.tmp)
CHARLIE_ADDR=$(cat address.charlie.tmp)


# funding the addresses (mine)
bitcoin-cli generatetoaddress 400 $ALICE_ADDR # 400 because we need at least 300 to activate segwit
bitcoin-cli generatetoaddress 100 $CHARLIE_ADDR


# see the UTXOs of this wallet
lcli-alice listfunds
lcli-bob listfunds
lcli-charlie listfunds


# connect the nodes
lcli-alice connect $BOB_ID localhost:10002
lcli-charlie connect $BOB_ID localhost:10002


# open channels
lcli-alice fundchannel $BOB_ID 10000000 | jq -r ".txid" > alice.funding.txid.tmp
bitcoin-cli generatetoaddress 6 $ALICE_ADDR # mine 6 blocks so the channel is considered valid. randomly crediting alice doesn't matter
lcli-charlie fundchannel $BOB_ID 10000000 | jq -r ".txid" > charlie.funding.txid.tmp
bitcoin-cli generatetoaddress 6 $ALICE_ADDR


# list open channels
lcli-bob listchannels


# make payment
lcli-bob invoice 1000000sat "label$(date +%s)" description | jq -r ".bolt11" > bolt11.tmp
lcli-charlie pay $(cat bolt11.tmp)


lcli-charlie invoice 1000000sat "label$(date +%s)" description | jq -r ".bolt11" > bolt11.tmp
lcli-alice pay $(cat bolt11.tmp)








# sending payment over channels
# create invoice (request for payment) and write the payment request to file
lncli-bob addinvoice --amt=10000 | jq -r ".pay_req" > invoice_pay_req.tmp
# lncli-bob listinvoices # list all invoices
lncli-alice sendpayment --pay_req=$(cat invoice_pay_req.tmp) # make the payment

# payment with hops
lncli-charlie addinvoice --amt=10000 | jq -r ".pay_req" > invoice_pay_req.tmp
lncli-alice sendpayment --pay_req=$(cat invoice_pay_req.tmp)


# close channel
# extract channel_point: unique channel identifier
lncli-alice listchannels | jq -r ".channels[0].channel_point" | cut -d':' -f1 > funding_txid.tmp
lncli-alice listchannels | jq -r ".channels[0].channel_point" | cut -d':' -f2 > output_idx.tmp
lncli-alice closechannel --funding_txid=$(cat funding_txid.tmp) --output_index=$(cat output_idx.tmp) > closing_txid.tmp
# mine a block with the closing transaction
btcctl --simnet --rpcuser=kek --rpcpass=kek generate 1
bitcoin-cli generatetoaddress 1 $(cat $LNPATH/dev/address.alice.tmp)

# check bob balance was updated on the blockchain
lncli-bob walletbalance


# get non-wallet transaction
gettransaction(){
    txid=$1
    bitcoin-cli getrawtransaction $txid > rawtransaction.tmp
    bitcoin-cli decoderawtransaction $(cat rawtransaction.tmp)
}
