#!/usr/bin/env bash

lcli-alice(){ lightning-cli --lightning-dir=$LNPATH/lightning-dirs/1 $*; }; export -f lcli-alice
lcli-bob(){ lightning-cli --lightning-dir=$LNPATH/lightning-dirs/2 $*; }; export -f lcli-bob
lcli-charlie(){ lightning-cli --lightning-dir=$LNPATH/lightning-dirs/3 $*; }; export -f lcli-charlie

gettransaction(){
    txid=$1
    RAW_TRANSACTION=$(bitcoin-cli getrawtransaction $txid)
    bitcoin-cli decoderawtransaction $RAW_TRANSACTION
}
export -f gettransaction

