#!/usr/bin/env bash

# run bitcoin node
run-btcd

# run LN nodes
run-lnd 1
run-lnd 2
run-lnd 3



# create wallet
lncli-alice create
lncli-bob create < $LNPATH/create-wallet-commands
lncli-charlie create


# get the nodes identity_pubkey
lncli-alice getinfo | jq -r ".identity_pubkey" > identity-pubkey-alice
lncli-bob getinfo | jq -r ".identity_pubkey" > identity-pubkey-bob
lncli-charlie getinfo | jq -r ".identity_pubkey" > identity-pubkey-charlie



# get addresses
lncli-alice newaddress np2wkh | jq -r ".address" > address.alice
lncli-bob newaddress np2wkh | jq -r ".address" > address.bob
lncli-charlie newaddress np2wkh | jq -r ".address" > address.charlie



# funding the addresses (mine)
btcd --simnet --txindex --rpcuser=kek --rpcpass=kek --miningaddr=$(cat address.alice)
btcctl --simnet --rpcuser=kek --rpcpass=kek generate 400  # 400 because we need at least 300 to activate segwit

btcd --txindex --simnet --rpcuser=kek --rpcpass=kek --miningaddr=$(cat address.charlie)
btcctl --simnet --rpcuser=kek --rpcpass=kek generate 100



# check wallet balance
lncli-alice walletbalance
lncli-bob walletbalance
lncli-charlie walletbalance



# connect the nodes
lncli-alice connect $(cat identity-pubkey-bob)@localhost:10012
lncli-bob connect $(cat identity-pubkey-charlie)@localhost:10012


