#!/usr/bin/env bash

I=$1

usage(){
    echo "$0 lnd_index"
}


if [[ -z $LNPATH ]]; then
    echo "LNPATH was not set"
    exit 1
fi

if [[ -z $I ]] ; then
    usage
    exit 1
fi

mkdir -p "$LNPATH/lnd/$I"
cd "$LNPATH/lnd/$I"

lnd \
    --rpclisten=localhost:1000${I} \
    --listen=localhost:1001${I} \
    --restlisten=localhost:800${I} \
    --datadir=data \
    --logdir=log \
    --debuglevel=info
