#!/usr/bin/env bash

# before running this script make sure:
#   1. the LNPATH variable was set
#   2. all daemons/clis directories are in PATH


cd $(dirname $0)

source cli-functions


# set conf files
BITCOIND_CONF="$HOME/.bitcoin/bitcoin.conf"
LND_CONF="$HOME/.lnd/lnd.conf"
cp "bitcoin.conf" "$BITCOIND_CONF"
cp "lnd.conf" "$LND_CONF"


BTCD_COMMAND="cd ${LNPATH}; bash"
ALICE_COMMAND="cd ${LNPATH}/dev/alice; bash"
BOB_COMMAND="cd ${LNPATH}/dev/bob; bash"
CHARLIE_COMMAND="cd ${LNPATH}/dev/charlie; bash"
LNCLI_COMMAND="cd dev; bash"


# kill any existing tmux sessions
tmux-kill

tmux new-session -d -n btcd "$BTCD_COMMAND"
tmux new-window -n a-lnd "$ALICE_COMMAND"
tmux new-window -n b-lnd "$BOB_COMMAND"
tmux new-window -n b-lnd "$CHARLIE_COMMAND"

tmux new-window -n cli "$LNCLI_COMMAND"

tmux select-window -t 0 # select active window
tmux attach-session
