#!/usr/bin/env bash

export LNPATH="/cs/usr/jonahar/ln"

source cli-functions


# commands to run in the different tmux windows
BTCD_COMMAND="cd ${LNPATH}; bash --init-file ${LNPATH}/dev-bashrc"
ALICE_COMMAND="cd ${LNPATH}/dev/alice; bash --init-file ${LNPATH}/dev-bashrc"
BOB_COMMAND="cd ${LNPATH}/dev/bob; bash --init-file ${LNPATH}/dev-bashrc"
CHARLIE_COMMAND="cd ${LNPATH}/dev/charlie; bash --init-file ${LNPATH}/dev-bashrc"
LNCLI_COMMAND="cd dev; bash --init-file ${LNPATH}/dev-bashrc"


# kill any existing tmux sessions
tmux-kill

tmux new-session -d -n btcd "$BTCD_COMMAND"
tmux new-window -n a-lnd "$ALICE_COMMAND"
tmux new-window -n b-lnd "$BOB_COMMAND"
tmux new-window -n b-lnd "$CHARLIE_COMMAND"

tmux new-window -n cli "$LNCLI_COMMAND"

tmux select-window -t 0 # select active window
tmux attach-session
