#!/usr/bin/env bash

# before running this script make sure:
#   1. the LNPATH variable was set
#   2. all daemons/clis directories are in PATH


cd $(dirname $0)

source cli-functions


# set conf files
ln -s -f "$LNPATH/conf/bitcoin.conf" "$HOME/.bitcoin/bitcoin.conf"
ln -s -f "$LNPATH/conf/lnd.conf" "$HOME/.lnd/lnd.conf"
ln -s -f "$LNPATH/conf/lightning.conf" "$HOME/.lightning/config"


# kill any existing tmux sessions
tmux-kill

tmux new-session -d -n btc-daemon
tmux new-window -n a-lnd
tmux new-window -n b-lnd
tmux new-window -n c-lnd
tmux new-window -n cli

tmux select-window -t 0 # select active window
tmux attach-session
