#!/usr/bin/env bash

lcli(){
    IDX=$1
    lightning-cli \
        --conf=$LN/conf/lightning.conf \
        --lightning-dir="$LN/lightning-dirs/$IDX" \
        "${@:2}"
}
export -f lcli

bcli(){
    IDX=$1
    BITCOIN_RPC_PORT_BASE=18000
    PORT=$((BITCOIN_RPC_PORT_BASE + IDX))
    bitcoin-cli -conf=$LN/conf/bitcoin.conf -rpcport=$PORT "${@:2}"
}
export -f bcli

bcli-main(){
    bcli 0 "$@"
}
export -f bcli-main

gettransaction(){
    txid=$1
    RAW_TRANSACTION=$(bcli-main getrawtransaction $txid)
    bcli-main decoderawtransaction $RAW_TRANSACTION
}
export -f gettransaction

getblock(){
    blockheight=$1
    blockhash=$(bcli-main getblockhash $blockheight)
    bcli-main getblock $blockhash
}
export -f getblock

mine(){
    BLOCKS_TO_MINE=$1
    bcli-main generatetoaddress $BLOCKS_TO_MINE $(bcli-main getnewaddress) > /dev/null
}
export -f mine
