#!/usr/bin/env bash

# the directory in which we put all nodes source code. MUST be an absolute path
ROOT_DIR="${HOME}/nodes"
cd "${ROOT_DIR}"

# Download and compile Berkeley DB (bitcoin-core dependency)
mkdir bdb
cd bdb
wget https://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
tar -xvf db-4.8.30.tar.gz
cd db-4.8.30
mkdir -p build_unix/build
BDB_PREFIX="$ROOT_DIR/bdb/db-4.8.30/build_unix/build"
chmod u+w dbinc/atomic.h # make file writeable
sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' dbinc/atomic.h # replace function name that may conflict with another
cd build_unix
../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
make install
cd "${ROOT_DIR}"

# make sure libzmq is installed. required for bitcoind to work with lnd
sudo apt install libzmq3-dev

# download and compile bitcoin-core
git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin
git checkout v0.19.0.1 # select the wanted version
./autogen.sh
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --with-zmq --enable-zmq
make
cd "${ROOT_DIR}"

# download and compile c-lightning
git clone https://github.com/ElementsProject/lightning.git
cd lightning
git checkout v0.8.0
./configure
make

# download GO version 1.13
cd "${ROOT_DIR}"
wget https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz
mkdir goroot
tar -C goroot -xzf go1.13.6.linux-amd64.tar.gz
export GOROOT="${ROOT_DIR}/goroot/go"
export GOPATH="${ROOT_DIR}/gopath/go"
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# download and compile LND
go get -d github.com/lightningnetwork/lnd # this takes a while
cd $GOPATH/src/github.com/lightningnetwork/lnd
git checkout v0.9.0-beta
make
