#!/usr/bin/env bash

IN=$1
OUT=$2

if [[ -z $IN ]] || [[ -z $OUT ]]; then
  echo "usage: dot2jpg INPUT.dot OUTPUT.jpg [dpi=300]"
  exit 1
fi

DPI=300
if [[ ! -z $3 ]]; then
  DPI=$3
fi

dot -Tjpg -Gdpi=300 $IN -o $OUT
