#!/usr/bin/env bash

BITCOIN_CLI="/cs/labs/avivz/jonahar/bitcoin-datadir/bitcoin-cli"

NUM_BLOCKS=$1
OUTFILE=$2

if [[ -z $NUM_BLOCKS ]]; then
  NUM_BLOCKS=1000 # 1000 blocks ~1 week
fi

if [[ -z $OUTFILE ]]; then
  SAMPLES_DIR="$LN/fee-statistics"
  mkdir -p $SAMPLES_DIR
  OUTFILE="$SAMPLES_DIR/minfeerates"
fi

HEIGHT=$($BITCOIN_CLI -getinfo | jq -r ".blocks")

echo "block_timestamp,minfeerate" >>$OUTFILE
for i in $(seq $((HEIGHT - NUM_BLOCKS + 1)) $HEIGHT); do
  printf "${i}," >>$OUTFILE
  $BITCOIN_CLI getblockstats $i | jq ".minfeerate" >>$OUTFILE
done
