#!/usr/bin/env bash

# generate transactions + mine

ADDR=$(bcli 0 getnewaddress)
bcli 0 generatetoaddress 150 $ADDR >/dev/null # at least 100 to unlock coinbase outputs

NUM_BLOCKS=20
TX_PER_BLOCK=100

for i in $(seq 0 $NUM_BLOCKS); do
  ADDR=$(bcli 0 getnewaddress)
  for j in $(seq 0 $TX_PER_BLOCK); do
    AMOUNT=$(printf '0.%04d\n' $RANDOM)
    bcli 0 sendtoaddress $ADDR $AMOUNT >/dev/null
  done
  # mine
  bcli 0 generatetoaddress 1 $ADDR >/dev/null
done
