#!/usr/bin/env bash

# generate blocks with transactions

ADDR=$(bcli 0 getnewaddress)
bcli 0 generatetoaddress 150 $ADDR >/dev/null # at least 100 to unlock coinbase outputs

NUM_BLOCKS=50
TX_PER_BLOCK=1

for i in $(seq 0 $NUM_BLOCKS); do
    ADDR=$(bcli 0 getnewaddress)
    for j in $(seq 0 $TX_PER_BLOCK); do
        AMOUNT=$(printf '0.%04d\n' $RANDOM)
        bcli 0 sendtoaddress $ADDR $AMOUNT >/dev/null
    done
    # mine the generated transactions
    bcli 0 generatetoaddress 1 $ADDR >/dev/null
done
