#!/usr/bin/env bash

# generate blocks with transactions

NUM_BLOCKS=$1
TX_PER_BLOCK=$2

if [[ -z $NUM_BLOCKS ]]; then
    NUM_BLOCKS=10
fi

if [[ -z $TX_PER_BLOCK ]]; then
    TX_PER_BLOCK=300
fi

gen_addr() {
    bcli 0 getnewaddress
}

ADDR=$(gen_addr)
bcli 0 generatetoaddress 150 $ADDR >/dev/null # at least 100 to unlock coinbase outputs

BATCH_SIZE=10

sendmany_arg="
{
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1,
\"$(gen_addr)\": 1
}
"

for i in $(seq 0 $NUM_BLOCKS); do
    for _ in $(seq 0 $((TX_PER_BLOCK / BATCH_SIZE))); do
        for _ in $(seq 0 $BATCH_SIZE); do
            bcli 0 sendmany "" "$sendmany_arg" >/dev/null &
        done
        wait # wait for the batch to finish
    done
    # mine the generated transactions
    bcli 0 generatetoaddress 1 $ADDR >/dev/null
    echo "mined $((i + 1)) blocks out of $NUM_BLOCKS"
done
