#!/usr/bin/env bash

# generate transactions + mine


ADDR=$(bitcoin-cli getnewaddress)
bitcoin-cli generatetoaddress 150 $ADDR > /dev/null  # at least 100 to unlock coinbase outputs

NUM_BLOCKS=20
TX_PER_BLOCK=10

for i in $( seq 0 $NUM_BLOCKS ); do
    ADDR=$(bitcoin-cli getnewaddress)
    for j in $( seq 0 $TX_PER_BLOCK ); do
        AMOUNT=$(printf '0.%04d\n' $RANDOM)
        bitcoin-cli sendtoaddress $ADDR $AMOUNT > /dev/null
    done
    # mine
    bitcoin-cli generatetoaddress 1 $ADDR > /dev/null
done
