#!/usr/bin/env bash

pkill --signal SIGKILL lightningd
pkill --signal SIGKILL lnd
# eclair nodes store their pid in files
find /tmp/lightning-simulations -name "node_pid" -exec pkill --signal SIGKILL --pidfile "{}" ";" > /dev/null 2>&1
pkill --signal SIGKILL bitcoind
sleep 1
