#!/usr/bin/env bash

# one victim
AMOUNT_MSAT=20000000 # 0.0002 BTC
NUM_PAYMENTS=500 # extra more, just to be on the safe side
NUM_BLOCKS=200 # blocks to mine in the steal attack
TOPOLOGY="topologies/topology-simple.json"
DIR="simulations/simple"

cd $LN
source sh/cli-functions
clean-env

python3 py/commands_generator.py \
    --topology $TOPOLOGY \
    --establish-channels \
    --make-payments 1 3 $NUM_PAYMENTS $AMOUNT_MSAT \
    --steal-attack 1 3 $NUM_BLOCKS \
    --dump-data $DIR \
    --block-time 120 \
    --outfile generated_setup_commands

source generated_setup_commands
