#!/usr/bin/env bash

I=$1

usage(){
    echo "$0 NODE_INDEX [more lightningd args]*"
}


if [[ -z $LNPATH ]]; then
    echo "LNPATH was not set"
    exit 1
fi

if [[ -z $I ]]; then
    echo "please specify node index"
    usage
    exit 1
fi

mkdir -p "$LNPATH/lightning-dirs/$I"
cd "$LNPATH/lightning-dirs"

lightningd \
    --conf=$LNPATH/conf/lightning.conf \
    --lightning-dir=$I \
    --addr=localhost:1000${I} \
    --alias="node-number-$I" \
    "${@:2}"


# "${@:2}" gives us all the arguments starting from index 2, as separate tokens
# "${*:2}" would pass them as a single string