#!/usr/bin/env bash

BITCOIN_CLI="/cs/labs/avivz/jonahar/bitcoin-datadir/bitcoin-cli"
SAMPLES_DIR="$LN/fee-statistics"
mkdir -p $SAMPLES_DIR
cd $SAMPLES_DIR

sample() {
    for n in 2 4 100; do
        for mode in ECONOMICAL CONSERVATIVE; do
            outfile="estimatesmartfee_blocks=${n}_mode=${mode}"
            printf '%(%s)T,' >>${outfile} # current unix time and comma separator
            $BITCOIN_CLI estimatesmartfee ${n} ${mode} | jq -r ".feerate" >>${outfile}
        done
    done
}

while true; do
    sample
    sleep 60
done
