#!/usr/bin/env bash

# usgae: setup-tmux [scratch] 
# 
# create the following tmux windows and attach:
# - 1 bitcoind window
# - 3 lightningd windows
# - 1 cli window (bash)
# - 1 py3 window
# - 1 optional boot window (if 'scratch' argument was given)


cd $LNPATH
# lightning nodes are sleeping to avoid race condition with bitcoind
tmux new-session -d -n btc-daemon "bash -i -c 'bitcoind'"
tmux new-window -n a-lnd "bash -i -c 'sleep 1; run-lightningd 1'"
tmux new-window -n b-lnd "bash -i -c 'sleep 1; run-lightningd 2'"
tmux new-window -n c-lnd "bash -i -c 'sleep 1; run-lightningd 3'"
tmux new-window -n b-cli "cd dev; bash"
tmux new-window -n py3 "cd py; python3"

ACTIVE_WINDOW=5

if [[ "$1" == "scratch" ]]; then
    tmux new-window -n "boot" "bash -i -c 'sleep 2; env-boot'"
    ACTIVE_WINDOW=6
fi

tmux select-window -t $ACTIVE_WINDOW # select active window
tmux attach-session
