#!/usr/bin/env bash

usage(){
    echo """setup-env --topology TOPOLOGY_FILE [OPTIONS]

Setup a complete environment with bitcoin and lightning nodes running, connected
according to a given topology

Valid arguments
-t, --topology TOPOLOGY_FILE    topology json file. defaults to 'topology.json'
-s, --scratch                   setup from scratch (delete all data and establish channels
                                from scratch)
-h, --help                      display this help and exit
"""
    exit 1
}


parse-args(){
    # set default values
    TOPOLOGY="topology.json"
    SCRATCH="false"
    while [[ $# -gt 0 ]]; do
        key="$1"
        case $key in
            -s|--scratch)
                SCRATCH="true"
                shift
                ;;
            -t|--topology)
                TOPOLOGY="$2"
                shift 2
                ;;
            -h|--help)
                usage
                ;;
        esac
    done
}


parse-args "$@"

if [[ ! -f "$TOPOLOGY" ]]; then
    echo "topology file '$TOPOLOGY' does not exist"
    exit 1
fi

cd $LN
source sh/cli-functions

if [[ "$SCRATCH" == "true" ]]; then
    clean-env
    PYTHONPATH=$LN/py python3 -m commands_generator.commands_generator \
        --topology $TOPOLOGY \
        --outfile generated_setup_commands \
        --establish-channels
else
    kill-daemons
    PYTHONPATH=$LN/py python3 -m commands_generator.commands_generator \
        --topology $TOPOLOGY \
        --outfile generated_setup_commands
fi

source generated_setup_commands
tmux new-session -d -n cli

ACTIVE_WINDOW=0
tmux select-window -t $ACTIVE_WINDOW # select window on which we start when attaching
tmux attach-session
