#!/usr/bin/env bash

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --scratch)
            SCRATCH="scratch"
            shift
            ;;
    esac
done


source cli-functions
setup-configs
kill-daemons
setup-tmux $SCRATCH

