#!/usr/bin/env bash

# one victim
AMOUNT_MSAT=20000000 # 0.0002 BTC
NUM_PAYMENTS=2500 # a bit more than possible, just to be on the safe side
NUM_BLOCKS=180 # blocks to mine in the steal attack
BLOCK_TIME=180 # 3 minutes between two blocks, so ln nodes have enough time to do what they need
TOPOLOGY="topologies/topology-1-5-1.json"
DIR="simulations/steal-attack-1-5-1"

cd $LN
source sh/cli-functions
clean-env

python3 py/commands_generator.py \
    --topology $TOPOLOGY \
    --establish-channels \
    --make-payments 1 3 $NUM_PAYMENTS $AMOUNT_MSAT \
    --steal-attack 1 3 $NUM_BLOCKS \
    --dump-data $DIR \
    --block-time $BLOCK_TIME \
    --outfile generated_setup_commands

source generated_setup_commands
