#!/usr/bin/env bash


# configure a remote that points to the upstream repository (only needed once)
git remote add upstream git@github.com:ElementsProject/lightning.git
# verify upstream was added
git remote -v

# ----------------

git fetch upstream
git checkout master
git merge upstream/master
