#!/usr/bin/env bash

TOPOLOGY=$1
DATADIR=$2
NUM_PAYMENTS=$3
AMOUNT_MSAT=$4
NUM_BLOCKS=$5
BLOCK_TIME=$6
BITCOIN_BLOCKMAXWEIGHT=$7

cd $LN
source sh/cli-functions
clean-env

python3 py/commands_generator.py \
    --topology "$TOPOLOGY" \
    --establish-channels \
    --make-payments 1 3 $NUM_PAYMENTS $AMOUNT_MSAT \
    --steal-attack 1 3 $NUM_BLOCKS \
    --dump-data "$DATADIR" \
    --block-time $BLOCK_TIME \
    --bitcoin-blockmaxweight $BITCOIN_BLOCKMAXWEIGHT \
    --outfile generated_setup_commands

source generated_setup_commands
